#ifndef HARNESS_ABI_H
#define HARNESS_ABI_H

#include <stdint.h>

enum {
    HARNESS_STAGE_BOOT = 0,
    HARNESS_STAGE_AFTER_INIT = 1,
    HARNESS_STAGE_BEFORE_READ = 2,
    HARNESS_STAGE_AFTER_READ = 3,
    HARNESS_STAGE_AFTER_CHECKPOINT = 4,
    HARNESS_STAGE_AFTER_MUTATION = 5,
    HARNESS_STAGE_BEFORE_COMMIT = 6,
    HARNESS_STAGE_AFTER_COMMIT = 7,
};

enum {
    HARNESS_FAULT_NONE = 0,
    HARNESS_FAULT_COPY_A = 1,
    HARNESS_FAULT_ALL_DISTINCT = 2,
    HARNESS_FAULT_ACTIVE_VALUE = 10,
    HARNESS_FAULT_ACTIVE_LENGTH = 11,
    HARNESS_FAULT_ACTIVE_CHECKSUM = 12,
    HARNESS_FAULT_CHECKPOINT_VALUE = 13,
    HARNESS_FAULT_CHECKPOINT_CHECKSUM = 14,
    HARNESS_FAULT_ACTIVE_VALUE_AND_CHECKPOINT_CHECKSUM = 15,
};

enum {
    HARNESS_STATUS_OK = 0,
    HARNESS_STATUS_NO_MAJORITY = 1,
};

enum {
    HARNESS_RESTART_COMMITTED = 0,
    HARNESS_RESTART_RESTORED = 1,
    HARNESS_RESTART_RESTORE_FAILED = 2,
};

#endif
